# File: .github/workflows/workflow.yml 

name: Terraform Deployment to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
env:
  TF_VERSION: 1.5.0

jobs:
  build-and-deploy:
    name: Terraform Apply to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure using SPN credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Must be JSON with clientId, clientSecret, subscriptionId, tenantId
          enable-AzPSSession: true

      - name: Display Azure Subscription Info (Optional)
        run: az account show
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

        
      - name: Register Azure Providers
        run: |
          az provider register --namespace Microsoft.ContainerService
          az provider register --namespace Microsoft.Network
          az provider register --namespace Microsoft.Compute
          az provider register --namespace Microsoft.Storage

          
      - name: Set Terraform environment variables for backend authentication
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Validate
        run: terraform validate
  
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
